# Generated by Django 6.0.2 on 2026-02-22 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenderss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Infrastructure', 'Infrastructure'), ('Construction', 'Construction'), ('Road & Highway', 'Road & Highway'), ('Water Supply', 'Water Supply'), ('IT & Software', 'IT & Software'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Energy & Power', 'Energy & Power')], max_length=100)),
                ('description', models.TextField()),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('emd_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('publish_date', models.DateField()),
                ('closing_date', models.DateField()),
                ('pre_bid_meeting', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('draft', 'Draft')], default='open', max_length=20)),
                ('document', models.FileField(upload_to='tender_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
