# Generated by Django 6.0.1 on 2026-03-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderss',
            name='tender_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
