# Generated by Django 6.0.1 on 2026-03-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_tenderss_tender_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderss',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
