# Generated by Django 6.0.1 on 2026-03-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_alter_tenderss_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderss',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('draft', 'Draft'), ('awarded', 'Awarded')], default='open', max_length=20),
        ),
    ]
