# Generated by Django 6.0.2 on 2026-02-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('creator', 'Tender Creator / Department'), ('bidder', 'Bidder / Vendor')], max_length=20),
        ),
    ]
