# Generated by Django 6.0.2 on 2026-02-25 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
