# Generated by Django 6.0.2 on 2026-03-01 11:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_tenderapplication_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderapplication',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
