# Generated by Django 6.0.2 on 2026-03-01 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_alter_tenderapplication_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenderapplication',
            name='created_at',
        ),
    ]
